### ISSUE TITLE
Fenix Framework applications don't compile with Maven 3.1.0

### ISSUE THREAD

**Issue by jcarvalho** [fenix-framework/fenix-framework#174]
When attempting to compile a Fenix Framework based application with Maven 3.1.0, the following error is shown when running the ft-generate-domain goal.

```
org.apache.maven.lifecycle.LifecycleExecutionException: 
Failed to execute goal pt.ist:ff-maven-plugin:2.2.0:ff-generate-domain (default) on project fenix: 
An API incompatibility was encountered during configuration of mojo pt.ist:ff-maven-plugin:2.2.0:ff-generate-domain: 
java.lang.NoSuchMethodError: org.codehaus.plexus.component.configurator.converters.special.ClassRealmConverter.<init>(Lorg/codehaus/classworlds/ClassRealm;)V
```

With the stacktrace

```
Caused by: java.lang.NoSuchMethodError: org.codehaus.plexus.component.configurator.converters.special.ClassRealmConverter.<init>(Lorg/codehaus/classworlds/ClassRealm;)V
    at pt.ist.fenixframework.maven.IncludeProjectDependenciesComponentConfigurator.configureComponent(IncludeProjectDependenciesComponentConfigurator.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.component.configurator.AbstractComponentConfigurator.configureComponent(AbstractComponentConfigurator.java:57)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:572)
    ... 22 more
```

Line 45 of IncludeProjectDependenciesComponentConfigurator uses a deprecated constructor for the class `ClassRealmConverter`, which has been removed in Maven 3.1.0.

What is the goal of the `IncludeProjectDependenciesComponentConfigurator` class, that is repeated 3 times, one for each of the Maven plugins?
